# Generated by Django 6.1.1 on 2026-10-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_DB',
            fields=[
                ('reg_no', models.IntegerField()),
                ('name', models.CharField(max_length=28)),
                ('address', models.TextField()),
                ('campany', models.CharField(max_length=10)),
                ('model', models.CharField(max_length=10)),
                ('licence_num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('num_plate', models.IntegerField()),
            ],
        ),
    ]
